=== amangil1010/LMSGI_UD4/Clientes/Empresa.dtd
<?xml version="1.0" encoding = "UTF-8" ?>
<!ELEMENT Clientes (Sede*)>
<!ELEMENT Sede (Direcciones,Nombre_Del_Empleado,Fecha_Del_Alta,Descripcion,Cliente*)>
<!ATTLIST Sede Codigo CDATA #REQUIRED>
<!ELEMENT Direcciones (#PCDATA)>
<!ELEMENT Nombre_Del_Empleado (#PCDATA)>
<!ELEMENT Fecha_Del_Alta (#PCDATA)>
<!ELEMENT Descripcion (#PCDATA)>
<!ELEMENT Cliente (Numero_De_Viviendas,Coste,Resumen,Plazo)>
<!ATTLIST Cliente Codigo CDATA #REQUIRED>
<!ELEMENT Numero_De_Viviendas (#PCDATA)>
<!ELEMENT Coste (#PCDATA)>
<!ELEMENT Resumen (#PCDATA)>
<!ELEMENT Plazo (#PCDATA)>

=== amangil1010/LMSGI_UD4/Clientes/Empresa_X.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--<!DOCTYPE Clientes SYSTEM "Empresa.dtd">-->
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SOL_Empresa.xsd">    
    <Sede codigo="A0000000">
        <Direcciones>Arcos</Direcciones>
        <Nombre_Del_Empleado>Seat</Nombre_Del_Empleado>
        <Fecha_Del_Alta>2022-02-22</Fecha_Del_Alta>
        <Descripcion>8765 DMK</Descripcion>
        <Cliente codigo="AAA-000">
            <Numero_De_Viviendas>Seat</Numero_De_Viviendas>
            <Coste>Ibiza</Coste>
            <Resumen>8765 DMK</Resumen>
            <Plazo>12</Plazo>
        </Cliente>
    </Sede>
    <Sede codigo="A0000000">
        <Direcciones>Jerez</Direcciones>
        <Nombre_Del_Empleado>Porche</Nombre_Del_Empleado>
        <Fecha_Del_Alta>2022-03-03</Fecha_Del_Alta>
        <Descripcion>8765 DMK</Descripcion>
        <Cliente codigo="AAA-000">
            <Numero_De_Viviendas>Porche</Numero_De_Viviendas>
            <Coste>Porche</Coste>
            <Resumen>8765 DMK</Resumen>
            <Plazo>12</Plazo>
        </Cliente>
    </Sede>
</Clientes>

=== amangil1010/LMSGI_UD4/ClientesV2/Empresa_XV2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--<!DOCTYPE Clientes SYSTEM "Empresa.dtd">-->
<Clientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SOL_EmpresaV2.xsd">    
    <Sede codigo="A0000000">
        <Direcciones>Arcos</Direcciones>
        <Direcciones>Jerez</Direcciones>
        <Nombre_Del_Empleado>Seat</Nombre_Del_Empleado>
        <Fecha_Del_Alta>2022-02-22</Fecha_Del_Alta>
        <Descripcion>8765 DMK</Descripcion>
        <Cliente codigo="AAA-000">
            <Numero_De_Viviendas>1</Numero_De_Viviendas>
            <vivienda ID="001">
                <Coste>2</Coste>
                <Resumen>8765 DMK</Resumen>
                <Plazo>12</Plazo>
            </vivienda>
        </Cliente>
    </Sede>
    <Sede codigo="A0000000">
        <Direcciones>Jerez</Direcciones>
        <Direcciones>Jerez</Direcciones>
        <Nombre_Del_Empleado>Porche</Nombre_Del_Empleado>
        <Fecha_Del_Alta>2022-03-03</Fecha_Del_Alta>
        <Descripcion>8765 DMK</Descripcion>
        <Cliente codigo="AAA-000">
            <Numero_De_Viviendas>2</Numero_De_Viviendas>
            <vivienda ID="001">
                <Coste>2</Coste>
                <Resumen>8765 DMK</Resumen>
                <Plazo>12</Plazo>
            </vivienda>
        </Cliente>
    </Sede>
</Clientes>

=== amangil1010/LMSGI_UD4/Empresa/Empresa.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE Clientes SYSTEM "Empresa.dtd">
<Clientes>
        <Sede Codigo ='Aaaaaaaa'>
            <Direcciones>Arcos</Direcciones>
            <Nombre_Del_Empleado>Seat</Nombre_Del_Empleado>
            <Fecha_Del_Alta>Ibiza</Fecha_Del_Alta>
            <Descripcion>8765 DMK</Descripcion>
            <Cliente Codigo ='AAA-001'>
                <Numero_De_Viviendas>Seat</Numero_De_Viviendas>
                <Coste>Ibiza</Coste>
                <Resumen>8765 DMK</Resumen>
                <Plazo></Plazo>
            </Cliente>
        </Sede>
</Clientes>
